# config file version. Don't edit!
version = 3

[general]
verifyHost = ""
otpTime = 180
useWhitelist = true

[discord]
token = "token"
setNickname = false
guildID = 0
newbieRoleID = 0
verifyChannelID = 0
unverifyChannelID = 0

[mariadb]
url = "jdbc:mariadb://localhost:3306/dislinkmc"
user = "root"
password = "password"

[message]
# Placeholder: <name>, <uuid>, <code>
# Below messages use MiniMessage Format.
# https://docs.advntr.dev/minimessage/index.html
prefix = "<dark_aqua><b>DislinkMC Verify System</b></dark_aqua>"
onSuccess = "<yellow><name>'s code : <code></yellow>"
onFail = "<yellow>Fail to generate <name>'s code</yellow>"
onAlready = "<yellow><name> is already linked with Discord</yellow>"
onNotVerified = "<yellow><name> is not linked with Discord. Retry after link account with Discord</yellow>"