# config file version. Don't edit!
version = 1

[redis]
# url of redis server
url = "redis://localhost:6379"

[message]
# Placeholder: username : {0}, UUID : {1}, code: {2}
# Message uses java's MessageFormat.
# https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/text/MessageFormat.html
onSuccess = """§3§lDislinkMC Verify System§r

§e{0}''s code : {2}"""
onFail = """§3§lDislinkMC Verify System§r

§eFail to generate {0}''s code"""

[otp]
# OTP Code time limit in seconds
time = 180

